chore(version): increase default version; remove pid dir on clean; update pillar.example
saltstack-formulas/postgres-formula pull request #313
Opened 2021-06-06 20:33 UTC by noelmcloughlin

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

### Describe the changes you're proposing

This PR is minor:
- use more modern version as default
- remove /var/run/postgresql if it exists on clean
- update pillar.example version and note on CIDR

### Pillar / config required to test the proposed changes

### Debug log showing how the proposed changes work

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

2021-06-06 20:53 UTC, myii commented
@noelmcloughlin Testing this in the CI would mean adjusting this section here:

https://github.com/saltstack-formulas/postgres-formula/blob/1d34f8c56fc8254bab4d175e465915bd97dec0e1/test/salt/pillar/postgres.sls#L17-L22

Then we'll see which platforms can handle the given version number.

2021-06-06 23:15 UTC, myii requested changes
We can use `version: '13'` for testing across all platforms.

2021-06-06 23:15 UTC, myii commented on test/salt/pillar/postgres.sls
>    {%- endif %}
[Just checked](https://gitlab.com/myii/postgres-formula/-/pipelines/315779405), we no longer need the `if` block:

```suggestion
  version: '13'
```

2021-06-07 10:00 UTC, myii commented
@vutny Are you OK if `version: 13` is used throughout?

2021-06-09 20:57 UTC, noelmcloughlin commented
@myii thanks for the review - I implemented your suggested changes; version 13 should be fine across all OS.

2021-06-14 09:55 UTC, vutny approved these changes
Looks solid, tests are passing. Thanks!

2021-06-14 12:23 UTC, myii approved these changes

2021-06-14 12:23 UTC, merged

2021-06-14 12:23 UTC, myii commented
@noelmcloughlin Merged, thanks for the PR.
Appreciate the review, @vutny.